### ISSUE TITLE
Feature Request: Set the log time when pressing "done" rather than at the ping time

### ISSUE THREAD

**Issue by weverett** [dreeves/TagTime#68]
In the android app, if someone doesn't notice that the ping when it happens and just responds to the notification the time will be wrong.

**Comment by dreeves** [comment]
Thanks for this suggestion! It's an interesting point but I actually disagree with it. Pings happen when they happen and the UI needs to be clear that when you notice a ping from earlier that it's asking what you were doing *then*. 

I think that's also why it's important for TagTime to make a distinctive noise or otherwise do something attention-grabbing. That way you always know the exact moment the ping prompt is asking about. If you missed it then you may have to guess a bit.

But "when you noticed the ping prompt" is too fuzzy.

**Comment by Insti** [comment]
Seconded.

You need to respond what you were doing at the time of the ping, not when you noticed the notification. 
I tag missed pings as 'Unknown' and try to be better about paying attention to them in future.

**Comment by weverett** [comment]
I don't use TagTime for the purpose of tracking what I'm doing so the intended use case doesn't apply to me. It is okay that the feature request is denied for being out of scope.
